### PR TITLE
muted error  when building via carthage v0.18 in swift 3

### PR DESCRIPTION
**Pull request by keyOfVv**
muted error `UIView+ChameleonPrivate.m:25:21: error: receiver type 'UIWindow' for instance message is a forward declaration` when building via carthage v0.18 in swift 3

### CODE REVIEW

**Comment by keyOfVv** [comment]
Carthage v0.18 compiles with both Xcode 8 / Swift 2.3 and Xcode 7 / Swift 2.2, doesn't support swift 3.0 yet. So I think errors like this won't be raised in future. This PR is just a workaround at the moment. 
Build binary manually and drag it into project works fine too.
